# Generated by Django 4.2.7 on 2024-02-19 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='avg_rating',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='number_rating',
        ),
    ]
